# Generated by Django 4.1.4 on 2022-12-16 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('Email', models.EmailField(max_length=254)),
                ('Name', models.CharField(max_length=30)),
                ('IdNumber', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Birthday', models.DateField(verbose_name='Birthday')),
                ('Sex', models.CharField(max_length=20)),
                ('Telephone', models.IntegerField()),
                ('ParentPhone', models.IntegerField()),
                ('SelfPhone', models.IntegerField()),
                ('EmergePhone', models.IntegerField()),
                ('Address', models.CharField(max_length=254)),
                ('EmergencyName', models.CharField(max_length=254)),
                ('School', models.CharField(max_length=254)),
                ('Major', models.CharField(max_length=254)),
                ('Club', models.CharField(max_length=254)),
                ('SpecialDietary', models.CharField(max_length=254)),
                ('SpecialDisease', models.CharField(max_length=254)),
                ('FB', models.CharField(max_length=254)),
                ('GroupApply', models.BooleanField()),
                ('Picture', models.ImageField(upload_to='')),
                ('Motivation', models.CharField(max_length=254)),
                ('ParentAgree', models.ImageField(upload_to='')),
                ('SweaterSize', models.CharField(max_length=254)),
                ('InformedFrom', models.CharField(max_length=254)),
                ('WantToSay', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='school',
            fields=[
                ('school_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('school_district', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accept', models.BooleanField()),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.personal')),
            ],
        ),
    ]
