# Generated by Django 3.2.12 on 2023-01-02 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applicant', '0005_auto_20221230_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_time', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=30)),
                ('id_number', models.CharField(max_length=10)),
                ('birthday', models.DateField()),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=20)),
                ('telephone', models.CharField(max_length=10, null=True)),
                ('parent_phone', models.CharField(max_length=10)),
                ('self_phone', models.CharField(max_length=10)),
                ('emergency_name', models.CharField(max_length=512)),
                ('address', models.CharField(max_length=512)),
                ('emerge_phone', models.CharField(max_length=10, null=True)),
                ('school', models.CharField(max_length=512)),
                ('major', models.CharField(max_length=512)),
                ('club', models.CharField(max_length=512, null=True)),
                ('special_dietary', models.CharField(max_length=512, null=True)),
                ('special_disease', models.CharField(max_length=512, null=True)),
                ('facebook', models.CharField(max_length=512, null=True)),
                ('group_apply', models.BooleanField()),
                ('picture', models.URLField(null=True)),
                ('motivation', models.TextField(null=True)),
                ('agreement', models.URLField(null=True)),
                ('sweater_size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('2L', '2L')], max_length=2)),
                ('want_to_say', models.CharField(blank=True, max_length=512, null=True)),
                ('phase', models.CharField(choices=[('earlybird', '早鳥'), ('normal', '一階')], max_length=512, null=True)),
                ('accept', models.BooleanField(default=False)),
                ('group_person1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='applicant.applicant')),
                ('group_person2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='applicant.applicant')),
                ('group_person3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='applicant.applicant')),
            ],
        ),
        migrations.RenameField(
            model_name='review',
            old_name='Score',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='review',
            name='Person',
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
        migrations.DeleteModel(
            name='Personal',
        ),
        migrations.AddField(
            model_name='applicant',
            name='reviewers',
            field=models.ManyToManyField(related_name='reviewers', through='applicant.Review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='applicant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='applicant.applicant'),
        ),
    ]
