# Generated by Django 4.1.4 on 2023-01-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0008_auto_20230102_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='self_introduction',
            field=models.TextField(null=True),
        ),
    ]
