# Generated by Django 3.2.12 on 2023-01-02 06:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applicant', '0009_auto_20230102_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='agreement',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='club',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='emerge_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='facebook',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='motivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phase',
            field=models.CharField(blank=True, choices=[('earlybird', '早鳥'), ('normal', '一階')], max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='reviewers',
            field=models.ManyToManyField(related_name='reviewers', through='applicant.Review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='self_introduction',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='special_dietary',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='special_disease',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='telephone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
