# Generated by Django 4.1.4 on 2023-01-02 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0009_alter_applicant_self_introduction'),
        ('applicant', '0011_alter_applicant_reviewers'),
    ]

    operations = [
    ]
