# Generated by Django 3.2.12 on 2023-01-02 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0009_alter_applicant_self_introduction'),
        ('applicant', '0011_alter_applicant_reviewers'),
    ]

    operations = [
    ]
