# Generated by Django 3.2.12 on 2023-01-02 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0012_merge_20230102_1213'),
        ('applicant', '0012_merge_20230102_1349'),
    ]

    operations = [
    ]
