# Generated by Django 3.2.12 on 2023-01-02 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applicant', '0013_merge_20230102_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='agreement',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='motivation',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='picture',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='reviewers',
            field=models.ManyToManyField(related_name='reviewers', through='applicant.Review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='telephone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
