# Generated by Django 4.1.4 on 2023-01-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0015_auto_20230103_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='emerge_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='id_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='parent_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='self_phone',
            field=models.CharField(max_length=20),
        ),
    ]
