# Generated by Django 3.2.12 on 2023-01-03 17:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applicant', '0015_auto_20230103_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='avg_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='reviewers',
            field=models.ManyToManyField(related_name='reviewers', through='applicant.Review', to=settings.AUTH_USER_MODEL),
        ),
    ]
