# Generated by Django 4.1.4 on 2023-01-03 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0016_alter_applicant_emerge_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='agreement',
            field=models.TextField(null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='picture',
            field=models.TextField(null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
