# Generated by Django 4.1.4 on 2023-01-04 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0016_auto_20230103_1754'),
        ('applicant', '0017_alter_applicant_agreement_alter_applicant_picture'),
    ]

    operations = [
    ]
